"""add_double_chance_purchase_table

Revision ID: 0039cd926ef9
Revises: 5b5e4dc83526
Create Date: 2026-01-09 12:15:38.797552

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0039cd926ef9'
down_revision = '5b5e4dc83526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doublechancepurchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['tguser.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['tguser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'buyer_id', 'year', 'day', name='unique_double_chance_purchase')
    )
    op.drop_index('ix_finalvoting_game_id', table_name='finalvoting')
    op.drop_index('ix_finalvoting_year', table_name='finalvoting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_finalvoting_year', 'finalvoting', ['year'], unique=False)
    op.create_index('ix_finalvoting_game_id', 'finalvoting', ['game_id'], unique=False)
    op.drop_table('doublechancepurchase')
    # ### end Alembic commands ###
