"""add_reroll_and_transfer_models

Revision ID: 7652a9fc7c37
Revises: 0039cd926ef9
Create Date: 2026-01-22 15:15:56.548518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7652a9fc7c37'
down_revision = '0039cd926ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаём новую таблицу ChatBank
    op.create_table('chatbank',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('balance', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('game_id')
    )

    # Создаём новую таблицу CoinTransfer
    op.create_table('cointransfer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('receiver_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('commission', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('day', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['receiver_id'], ['tguser.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['tguser.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Добавляем новые колонки в GameResult
    op.add_column('gameresult', sa.Column('reroll_available', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('gameresult', sa.Column('reroll_initiator_id', sa.Integer(), nullable=True))
    op.add_column('gameresult', sa.Column('original_winner_id', sa.Integer(), nullable=True))
    op.add_column('gameresult', sa.Column('reroll_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_gameresult_reroll_initiator', 'gameresult', 'tguser', ['reroll_initiator_id'], ['id'])
    op.create_foreign_key('fk_gameresult_original_winner', 'gameresult', 'tguser', ['original_winner_id'], ['id'])

    # Изменяем таблицу Prediction
    op.add_column('prediction', sa.Column('predicted_user_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Мигрируем данные из predicted_user_id в predicted_user_ids (JSON array с одним элементом)
    op.execute("UPDATE prediction SET predicted_user_ids = '[' || predicted_user_id || ']'")

    # Удаляем старую колонку
    op.drop_constraint('prediction_predicted_user_id_fkey', 'prediction', type_='foreignkey')
    op.drop_column('prediction', 'predicted_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Восстанавливаем predicted_user_id в Prediction
    op.add_column('prediction', sa.Column('predicted_user_id', sa.INTEGER(), nullable=True))

    # Мигрируем данные обратно (берём первый элемент из JSON array)
    op.execute("""
        UPDATE prediction
        SET predicted_user_id = CAST(
            REPLACE(REPLACE(predicted_user_ids, '[', ''), ']', '') AS INTEGER
        )
    """)

    op.create_foreign_key('prediction_predicted_user_id_fkey', 'prediction', 'tguser', ['predicted_user_id'], ['id'])
    op.drop_column('prediction', 'predicted_user_ids')

    # Удаляем новые колонки из GameResult
    op.drop_constraint('fk_gameresult_original_winner', 'gameresult', type_='foreignkey')
    op.drop_constraint('fk_gameresult_reroll_initiator', 'gameresult', type_='foreignkey')
    op.drop_column('gameresult', 'reroll_message_id')
    op.drop_column('gameresult', 'original_winner_id')
    op.drop_column('gameresult', 'reroll_initiator_id')
    op.drop_column('gameresult', 'reroll_available')

    # Удаляем новые таблицы
    op.drop_table('cointransfer')
    op.drop_table('chatbank')

    # ### end Alembic commands ###
