"""add_final_voting

Revision ID: b9f3d4e5c6a7
Revises: a8ac3c2ed821
Create Date: 2025-11-28 16:43:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b9f3d4e5c6a7'
down_revision = 'a8ac3c2ed821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finalvoting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('poll_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('poll_message_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('missed_days_count', sa.Integer(), nullable=False),
    sa.Column('missed_days_list', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['tguser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'year', name='unique_final_voting')
    )
    op.create_index(op.f('ix_finalvoting_game_id'), 'finalvoting', ['game_id'], unique=False)
    op.create_index(op.f('ix_finalvoting_year'), 'finalvoting', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finalvoting_year'), table_name='finalvoting')
    op.drop_index(op.f('ix_finalvoting_game_id'), table_name='finalvoting')
    op.drop_table('finalvoting')
    # ### end Alembic commands ###
