"""remove_unique_constraint_from_pidorcointransaction

Revision ID: c4e61e34981a
Revises: f1g2h3i4j5k6
Create Date: 2026-01-05 21:41:35.843358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4e61e34981a'
down_revision = 'f1g2h3i4j5k6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование constraint перед удалением (для совместимости с PostgreSQL)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    constraints = [c['name'] for c in inspector.get_unique_constraints('pidorcointransaction')]

    if 'idx_game_user_year' in constraints:
        op.drop_constraint('idx_game_user_year', 'pidorcointransaction', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_game_user_year', 'pidorcointransaction', ['game_id', 'user_id', 'year'])
    # ### end Alembic commands ###
