"""add_custom_voting_fields

Revision ID: c7d8e9f0a1b2
Revises: b9f3d4e5c6a7
Create Date: 2025-12-08 23:02:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = 'b9f3d4e5c6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finalvoting', sa.Column('votes_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='{}'))
    op.add_column('finalvoting', sa.Column('is_results_hidden', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('finalvoting', sa.Column('voting_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finalvoting', 'voting_message_id')
    op.drop_column('finalvoting', 'is_results_hidden')
    op.drop_column('finalvoting', 'votes_data')
    # ### end Alembic commands ###
