"""add_winners_data_to_finalvoting

Revision ID: d8e9f0a1b3c4
Revises: c7d8e9f0a1b2
Create Date: 2025-12-13 16:24:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd8e9f0a1b3c4'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finalvoting', sa.Column('winners_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finalvoting', 'winners_data')
    # ### end Alembic commands ###
