"""add_excluded_leaders_to_final_voting

Revision ID: e1f2g3h4i5j6
Revises: d8e9f0a1b3c4
Create Date: 2025-12-13 16:25:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1f2g3h4i5j6'
down_revision = 'd8e9f0a1b3c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finalvoting', sa.Column('excluded_leaders_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finalvoting', 'excluded_leaders_data')
    # ### end Alembic commands ###
