"""add_gameplayereffect_table

Revision ID: g2h3i4j5k6l7
Revises: f1g2h3i4j5k6
Create Date: 2026-01-07 19:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g2h3i4j5k6l7'
down_revision = 'f1g2h3i4j5k6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameplayereffect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('immunity_until', sa.DateTime(), nullable=True),
    sa.Column('immunity_last_used', sa.DateTime(), nullable=True),
    sa.Column('double_chance_until', sa.DateTime(), nullable=True),
    sa.Column('double_chance_bought_by', sa.Integer(), nullable=True),
    sa.Column('next_win_multiplier', sa.Integer(), nullable=False, server_default='1'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tguser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='unique_game_player_effect')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameplayereffect')
    # ### end Alembic commands ###
